---
- hosts: web
  become: yes
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present

    - name: Configure NGINX reverse proxy
      copy:
        dest: /etc/nginx/sites-available/webapp
        content: |
          server {
              listen 80;
              server_name _;
              location / {
                  proxy_pass http://127.0.0.1:5000;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Enable NGINX site
      command: ln -s /etc/nginx/sites-available/webapp /etc/nginx/sites-enabled/webapp

    - name: Restart NGINX
      service:
        name: nginx
        state: restarted

